port: 3009
lsi: false
permalink: /:title
markdown: kramdown
safe: false
exclude:
  - misc
  - _build
  - src
  - node_modules
  - package.json
  - package-lock.json
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
